import { CandidateCompetencesReport } from "@/lib/canidature/client";

export const data: CandidateCompetencesReport[] = [
  {
    name: "Juan",
    surname: "Perez",
    email: "a@e.s",
    phoneNumber: "123123123",
    competences: [
      { name: "competencia1", value: 71 },
      { name: "competencia2", value: 22 },
      { name: "competencia3", value: 20 },
      { name: "competencia4", value: 67 },
      { name: "competencia5", value: 20 },
      { name: "competencia6", value: 70 },
      { name: "competencia7", value: 20 },
      { name: "competencia8", value: 62 },
      { name: "competencia9", value: 9 },
      { name: "competencia10", value: 35 },
    ],
  },
  {
    name: "Manu",
    surname: "Ruiz",
    email: "abasd@ese.s",
    phoneNumber: "123123123",
    competences: [
      { name: "competencia1", value: 71 },
      { name: "competencia2", value: 22 },
      { name: "competencia3", value: 20 },
      { name: "competencia4", value: 67 },
      { name: "competencia5", value: 20 },
      { name: "competencia6", value: 70 },
      { name: "competencia7", value: 20 },
      { name: "competencia8", value: 62 },
      { name: "competencia9", value: 9 },
      { name: "competencia10", value: 35 },
    ],
  },
  {
    name: "Luis",
    surname: "Rodriguez",
    email: "best@es.be",
    phoneNumber: "123123123",
    competences: [
      { name: "competencia1", value: 48 },
      { name: "competencia2", value: 19 },
      { name: "competencia3", value: 9 },
      { name: "competencia4", value: 23 },
      { name: "competencia5", value: 38 },
      { name: "competencia6", value: 65 },
      { name: "competencia7", value: 37 },
      { name: "competencia8", value: 27 },
      { name: "competencia9", value: 26 },
      { name: "competencia10", value: 26 },
    ],
  },
  {
    name: "User834",
    surname: "LastName123",
    email: "user834.lastname123@example.com",
    phoneNumber: "358745883",
    competences: [
      { name: "competencia1", value: 48 },
      { name: "competencia2", value: 19 },
      { name: "competencia3", value: 9 },
      { name: "competencia4", value: 23 },
      { name: "competencia5", value: 38 },
      { name: "competencia6", value: 65 },
      { name: "competencia7", value: 37 },
      { name: "competencia8", value: 27 },
      { name: "competencia9", value: 26 },
      { name: "competencia10", value: 26 },
    ],
  },
  {
    name: "User854",
    surname: "LastName705",
    email: "user854.lastname705@example.com",
    phoneNumber: "131417220",
    competences: [
      { name: "competencia1", value: 25 },
      { name: "competencia2", value: 35 },
      { name: "competencia3", value: 47 },
      { name: "competencia4", value: 63 },
      { name: "competencia5", value: 48 },
      { name: "competencia6", value: 86 },
      { name: "competencia7", value: 52 },
      { name: "competencia8", value: 53 },
      { name: "competencia9", value: 34 },
      { name: "competencia10", value: 79 },
    ],
  },
  {
    name: "User809",
    surname: "LastName487",
    email: "user809.lastname487@example.com",
    phoneNumber: "141061041",
    competences: [
      { name: "competencia1", value: 87 },
      { name: "competencia2", value: 42 },
      { name: "competencia3", value: 68 },
      { name: "competencia4", value: 53 },
      { name: "competencia5", value: 63 },
      { name: "competencia6", value: 69 },
      { name: "competencia7", value: 60 },
      { name: "competencia8", value: 1 },
      { name: "competencia9", value: 35 },
      { name: "competencia10", value: 90 },
    ],
  },
  {
    name: "User3",
    surname: "LastName984",
    email: "user3.lastname984@example.com",
    phoneNumber: "789423236",
    competences: [
      { name: "competencia1", value: 33 },
      { name: "competencia2", value: 53 },
      { name: "competencia3", value: 59 },
      { name: "competencia4", value: 27 },
      { name: "competencia5", value: 12 },
      { name: "competencia6", value: 26 },
      { name: "competencia7", value: 38 },
      { name: "competencia8", value: 20 },
      { name: "competencia9", value: 29 },
      { name: "competencia10", value: 41 },
    ],
  },
  {
    name: "User782",
    surname: "LastName859",
    email: "user782.lastname859@example.com",
    phoneNumber: "513753937",
    competences: [
      { name: "competencia1", value: 71 },
      { name: "competencia2", value: 22 },
      { name: "competencia3", value: 20 },
      { name: "competencia4", value: 67 },
      { name: "competencia5", value: 20 },
      { name: "competencia6", value: 70 },
      { name: "competencia7", value: 20 },
      { name: "competencia8", value: 62 },
      { name: "competencia9", value: 9 },
      { name: "competencia10", value: 35 },
    ],
  },
];
